In [2]:
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot  as plt

In [8]:
path = r'C:\Users\darck\OneDrive\Desktop\sel_test\data_Maps'

In [9]:
data = pd.read_csv(path)

In [10]:
data.shape

(15, 5)

In [11]:
data.head()

,Unnamed: 0,Noms,Adresse,Reviews,Reviews_nbrs
0,0,Amrharhe Abdellatif,"Avenue Al Massira (C.Y.M), Amal 1, J5 , N°728 ...","4,5",22
1,1,El Yaagoubi Hind,"Appt. N° 2, 10100 Résid. Camélia 1, Rue Joulla...","4,4",20
2,2,Mahaj Clinique Dentaire,"Rue Al Ijjass, Rabat 10100","4,3",114
3,3,Centre Dentaire Spécialisé Dr Yasser Boukhal,"1er Étage , 569, Hay Al Massira, Amal 5, C.Y.M...","4,7",86
4,4,Cabinet Dentaire Docteur Aalloula El Houssaine,"Hay Ryad, Rue Al Ijjass Sect. 10 N°1, Rabat","5,0",1

In [12]:
data.drop_duplicates()

,Unnamed: 0,Noms,Adresse,Reviews,Reviews_nbrs
0,0,Amrharhe Abdellatif,"Avenue Al Massira (C.Y.M), Amal 1, J5 , N°728 ...","4,5",22
1,1,El Yaagoubi Hind,"Appt. N° 2, 10100 Résid. Camélia 1, Rue Joulla...","4,4",20
2,2,Mahaj Clinique Dentaire,"Rue Al Ijjass, Rabat 10100","4,3",114
3,3,Centre Dentaire Spécialisé Dr Yasser Boukhal,"1er Étage , 569, Hay Al Massira, Amal 5, C.Y.M...","4,7",86
4,4,Cabinet Dentaire Docteur Aalloula El Houssaine,"Hay Ryad, Rue Al Ijjass Sect. 10 N°1, Rabat","5,0",1
5,5,Clinique Dentaire Annakhil Riad,"10000, 27 Av. Annakhil, Rabat","4,1",19
6,6,Clinique Dentaire Riad,"Res Dar El Mehdi, 3 Rue Arromane, Rabat 10110","5,0",23
7,7,Berrahou Ikram,"144, Avenue Al Massira (C.Y.M) Diour Elmalk Bl...","3,4",5
8,8,Cabinet Dr DOUHAOUI BRAHIM,"j5 Av. Al Massira, Rabat","4,6",20
9,9,Guerbaz Fatima,"Hay Ryad, Résid. Almassafat Sect.10, 2°Ét. N°5...","4,6",10
10,10,LA CLINIQUE DENTAIRE DES NATIONS UNIES RABAT,"1ér étage, 92 Av. des Nations Unies, Rabat 10080","3,8",87
11,11,Clinique Dentaire Des Spécialités Rabat,"rez de chaussée, 92 Av. des Nations Unies, Rab...","3,2",41
12,12,Centre Dentaire ALMANAR,"2ieme étage, Complement Massira, 1004 Amal 5, ...","4,9",85
13,13,Cabinet Dentaire Spécialisé Bentayeb,Appartement n°1 Résidence Ryad Soundouss 2 Ang...,"4,7",90
14,14,Hadouche Younes,"16, Avenue Al Massira (C.Y.M) Amal 4, Rabat-Sa...","5,0",4

In [13]:
data.describe()

       Unnamed: 0  Reviews_nbrs
count   15.000000      15.00000
mean     7.000000      41.80000
std      4.472136      38.79838
min      0.000000       1.00000
25%      3.500000      14.50000
50%      7.000000      22.00000
75%     10.500000      85.50000
max     14.000000     114.00000

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    15 non-null     int64
 1   Noms          15 non-null     object
 2   Adresse       15 non-null     object
 3   Reviews       15 non-null     object
 4   Reviews_nbrs  15 non-null     int64
dtypes: int64(2), object(3)
memory usage: 732.0+ bytes

In [15]:
df = data.copy()

In [16]:
df.head()

,Unnamed: 0,Noms,Adresse,Reviews,Reviews_nbrs
0,0,Amrharhe Abdellatif,"Avenue Al Massira (C.Y.M), Amal 1, J5 , N°728 ...","4,5",22
1,1,El Yaagoubi Hind,"Appt. N° 2, 10100 Résid. Camélia 1, Rue Joulla...","4,4",20
2,2,Mahaj Clinique Dentaire,"Rue Al Ijjass, Rabat 10100","4,3",114
3,3,Centre Dentaire Spécialisé Dr Yasser Boukhal,"1er Étage , 569, Hay Al Massira, Amal 5, C.Y.M...","4,7",86
4,4,Cabinet Dentaire Docteur Aalloula El Houssaine,"Hay Ryad, Rue Al Ijjass Sect. 10 N°1, Rabat","5,0",1

In [17]:
df['Reviews'] = df['Reviews'].str.replace(',','.')

In [18]:
df['Reviews'] = df['Reviews'].astype('float64')

In [19]:
df = df.loc[df['Reviews_nbrs']>80]

In [20]:
df = df.loc[df['Reviews']>4.5]

In [21]:
#Les éléments conseillés
df

,Unnamed: 0,Noms,Adresse,Reviews,Reviews_nbrs
3,3,Centre Dentaire Spécialisé Dr Yasser Boukhal,"1er Étage , 569, Hay Al Massira, Amal 5, C.Y.M...",4.7,86
12,12,Centre Dentaire ALMANAR,"2ieme étage, Complement Massira, 1004 Amal 5, ...",4.9,85
13,13,Cabinet Dentaire Spécialisé Bentayeb,Appartement n°1 Résidence Ryad Soundouss 2 Ang...,4.7,90